### ISSUE TITLE
Security issue with GET request

### ISSUE THREAD

**Issue by Ben-random** [myl117/Password-Check-API#1]
https://github.com/myl117/Password-Check-API/blob/70abd8357dd202a29531889c0e9e8b5406110ddd/routes.js#L6

Since this is a get request and the route has no access to the request body, the password has to be exposed in the url. This is very unsafe as even in https (where data is encrypted and therefore secure), the password would still be exposed as it's in the url. A better way would be to use POST and have the password passed through to the route in the body. 

nit: Also, the caught exceptions in the try/accept would be caused by incorrectly formatted input, no? Then it should be a 400 return for a bad request or 401 if you want to pass back to the client that the user is unauthenticated.

Otherwise, looks good, great work!

**Comment by myl117** [comment]
Thanks for the feedback Ben! I've implemented the fixes.
